### 1.6.1_train_test_split

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)

X
list(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

X_train
y_train
X_test
y_test

train_test_split(y, shuffle=True)


[[1, 2, 4], [0, 3]]

### 1.6.2_KFold

In [2]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([11, 22, 33, 44])

nn = 2
#nn=3
#nn=4

kf = KFold(n_splits=nn)
kf.get_n_splits(X)
KFold(n_splits=nn, random_state=None, shuffle=False)

for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)


TRAIN: [2 3] TEST: [0 1]
X_train 
 [[5 6]
 [7 8]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [33 44]
y_test 
 [11 22]
TRAIN: [0 1] TEST: [2 3]
X_train 
 [[1 2]
 [3 4]]
X_test 
 [[5 6]
 [7 8]]
y_train 
 [11 22]
y_test 
 [33 44]


### 1.6.3_Repeated KFold

In [3]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([11, 22, 33, 44])


rkf = RepeatedKFold(n_splits=4, n_repeats=4, random_state=44)
for train_index, test_index in rkf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [5 6]]
X_test 
 [[7 8]]
y_train 
 [11 22 33]
y_test 
 [44]
*********************
TRAIN: [0 1 3] TEST: [2]
X_train 
 [[1 2]
 [3 4]
 [7 8]]
X_test 
 [[5 6]]
y_train 
 [11 22 44]
y_test 
 [33]
*********************
TRAIN: [0 2 3] TEST: [1]
X_train 
 [[1 2]
 [5 6]
 [7 8]]
X_test 
 [[3 4]]
y_train 
 [11 33 44]
y_test 
 [22]
*********************
TRAIN: [1 2 3] TEST: [0]
X_train 
 [[3 4]
 [5 6]
 [7 8]]
X_test 
 [[1 2]]
y_train 
 [22 33 44]
y_test 
 [11]
*********************
TRAIN: [0 2 3] TEST: [1]
X_train 
 [[1 2]
 [5 6]
 [7 8]]
X_test 
 [[3 4]]
y_train 
 [11 33 44]
y_test 
 [22]
*********************
TRAIN: [0 1 3] TEST: [2]
X_train 
 [[1 2]
 [3 4]
 [7 8]]
X_test 
 [[5 6]]
y_train 
 [11 22 44]
y_test 
 [33]
*********************
TRAIN: [1 2 3] TEST: [0]
X_train 
 [[3 4]
 [5 6]
 [7 8]]
X_test 
 [[1 2]]
y_train 
 [22 33 44]
y_test 
 [11]
*********************
TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [5 6]]
X_test 
 [[7 8]]
y_train 


In [4]:
import numpy as np
from sklearn.model_selection import RepeatedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
random_state = 12883823
rkf = RepeatedKFold(n_splits=2, n_repeats=2, random_state=random_state)
for train, test in rkf.split(X):
    print("%s %s" % (train, test))


[2 3] [0 1]
[0 1] [2 3]
[0 2] [1 3]
[1 3] [0 2]


### 1.6.4_Stratified_KFold

In [5]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([0,0,0,1])
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X, y)

print(skf)

for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [2 3] TEST: [0 1]
X_train 
 [[5 6]
 [7 8]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1]
y_test 
 [0 0]
*********************
TRAIN: [0 1] TEST: [2 3]
X_train 
 [[1 2]
 [3 4]]
X_test 
 [[5 6]
 [7 8]]
y_train 
 [0 0]
y_test 
 [0 1]
*********************


c:\users\olaab\appdata\local\programs\python\python37\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  % (min_groups, self.n_splits)), UserWarning)


### 1.6.5_Repeated_Stratified_KFold

In [6]:
import numpy as np
from sklearn.model_selection import RepeatedStratifiedKFold

X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([0,0,1,1])
rskf = RepeatedStratifiedKFold(n_splits=2, n_repeats=2,random_state=36851234)
for train_index, test_index in rskf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


TRAIN: [1 2] TEST: [0 3]
X_train 
 [[3 4]
 [5 6]]
X_test 
 [[1 2]
 [7 8]]
y_train 
 [0 1]
y_test 
 [0 1]
*********************
TRAIN: [0 3] TEST: [1 2]
X_train 
 [[1 2]
 [7 8]]
X_test 
 [[3 4]
 [5 6]]
y_train 
 [0 1]
y_test 
 [0 1]
*********************
TRAIN: [1 3] TEST: [0 2]
X_train 
 [[3 4]
 [7 8]]
X_test 
 [[1 2]
 [5 6]]
y_train 
 [0 1]
y_test 
 [0 1]
*********************
TRAIN: [0 2] TEST: [1 3]
X_train 
 [[1 2]
 [5 6]]
X_test 
 [[3 4]
 [7 8]]
y_train 
 [0 1]
y_test 
 [0 1]
*********************


### 1.6.6_Leave_One_Out

In [7]:
import numpy as np
from sklearn.model_selection import LeaveOneOut
X = np.array([1, 2, 3, 4])
y = np.array([5,6,7,8])
loo = LeaveOneOut()
loo.get_n_splits(X)
print(loo)
LeaveOneOut()
for train_index, test_index in loo.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


LeaveOneOut()
TRAIN: [1 2 3] TEST: [0]
X_train 
 [2 3 4]
X_test 
 [1]
y_train 
 [6 7 8]
y_test 
 [5]
*********************
TRAIN: [0 2 3] TEST: [1]
X_train 
 [1 3 4]
X_test 
 [2]
y_train 
 [5 7 8]
y_test 
 [6]
*********************
TRAIN: [0 1 3] TEST: [2]
X_train 
 [1 2 4]
X_test 
 [3]
y_train 
 [5 6 8]
y_test 
 [7]
*********************
TRAIN: [0 1 2] TEST: [3]
X_train 
 [1 2 3]
X_test 
 [4]
y_train 
 [5 6 7]
y_test 
 [8]
*********************


In [8]:
from sklearn.model_selection import LeaveOneOut
X = [1, 2, 3, 4]
loo = LeaveOneOut()
for train, test in loo.split(X):
    print("%s %s" % (train, test))
 


[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]


### 1.6.7_Leave_P_Out

In [9]:
import numpy as np
from sklearn.model_selection import LeavePOut
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 3, 4])
#lpo = LeavePOut(1)
#lpo = LeavePOut(2)
lpo = LeavePOut(3)

lpo.get_n_splits(X)

print(lpo)
LeavePOut(p=2)
for train_index, test_index in lpo.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


LeavePOut(p=3)
TRAIN: [3] TEST: [0 1 2]
X_train 
 [[7 8]]
X_test 
 [[1 2]
 [3 4]
 [5 6]]
y_train 
 [4]
y_test 
 [1 2 3]
*********************
TRAIN: [2] TEST: [0 1 3]
X_train 
 [[5 6]]
X_test 
 [[1 2]
 [3 4]
 [7 8]]
y_train 
 [3]
y_test 
 [1 2 4]
*********************
TRAIN: [1] TEST: [0 2 3]
X_train 
 [[3 4]]
X_test 
 [[1 2]
 [5 6]
 [7 8]]
y_train 
 [2]
y_test 
 [1 3 4]
*********************
TRAIN: [0] TEST: [1 2 3]
X_train 
 [[1 2]]
X_test 
 [[3 4]
 [5 6]
 [7 8]]
y_train 
 [1]
y_test 
 [2 3 4]
*********************


In [10]:
import numpy as np
from sklearn.model_selection import LeavePOut
X = np.ones(10)
lpo = LeavePOut(p=3)
for train, test in lpo.split(X):
    print("%s %s" % (train, test))


[3 4 5 6 7 8 9] [0 1 2]
[2 4 5 6 7 8 9] [0 1 3]
[2 3 5 6 7 8 9] [0 1 4]
[2 3 4 6 7 8 9] [0 1 5]
[2 3 4 5 7 8 9] [0 1 6]
[2 3 4 5 6 8 9] [0 1 7]
[2 3 4 5 6 7 9] [0 1 8]
[2 3 4 5 6 7 8] [0 1 9]
[1 4 5 6 7 8 9] [0 2 3]
[1 3 5 6 7 8 9] [0 2 4]
[1 3 4 6 7 8 9] [0 2 5]
[1 3 4 5 7 8 9] [0 2 6]
[1 3 4 5 6 8 9] [0 2 7]
[1 3 4 5 6 7 9] [0 2 8]
[1 3 4 5 6 7 8] [0 2 9]
[1 2 5 6 7 8 9] [0 3 4]
[1 2 4 6 7 8 9] [0 3 5]
[1 2 4 5 7 8 9] [0 3 6]
[1 2 4 5 6 8 9] [0 3 7]
[1 2 4 5 6 7 9] [0 3 8]
[1 2 4 5 6 7 8] [0 3 9]
[1 2 3 6 7 8 9] [0 4 5]
[1 2 3 5 7 8 9] [0 4 6]
[1 2 3 5 6 8 9] [0 4 7]
[1 2 3 5 6 7 9] [0 4 8]
[1 2 3 5 6 7 8] [0 4 9]
[1 2 3 4 7 8 9] [0 5 6]
[1 2 3 4 6 8 9] [0 5 7]
[1 2 3 4 6 7 9] [0 5 8]
[1 2 3 4 6 7 8] [0 5 9]
[1 2 3 4 5 8 9] [0 6 7]
[1 2 3 4 5 7 9] [0 6 8]
[1 2 3 4 5 7 8] [0 6 9]
[1 2 3 4 5 6 9] [0 7 8]
[1 2 3 4 5 6 8] [0 7 9]
[1 2 3 4 5 6 7] [0 8 9]
[0 4 5 6 7 8 9] [1 2 3]
[0 3 5 6 7 8 9] [1 2 4]
[0 3 4 6 7 8 9] [1 2 5]
[0 3 4 5 7 8 9] [1 2 6]
[0 3 4 5 6 8 9] [1 2 7]
[0 3 4 5 6 7 9] 

### 1.6.8_Shuffle_Split

In [11]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])
tscv = TimeSeriesSplit(n_splits=5)
print(tscv)
for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


TimeSeriesSplit(max_train_size=None, n_splits=5)
TRAIN: [0] TEST: [1]
X_train 
 [[1 2]]
X_test 
 [[3 4]]
y_train 
 [1]
y_test 
 [2]
*********************
TRAIN: [0 1] TEST: [2]
X_train 
 [[1 2]
 [3 4]]
X_test 
 [[1 2]]
y_train 
 [1 2]
y_test 
 [3]
*********************
TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [1 2]]
X_test 
 [[3 4]]
y_train 
 [1 2 3]
y_test 
 [4]
*********************
TRAIN: [0 1 2 3] TEST: [4]
X_train 
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]
X_test 
 [[1 2]]
y_train 
 [1 2 3 4]
y_test 
 [5]
*********************
TRAIN: [0 1 2 3 4] TEST: [5]
X_train 
 [[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]]
X_test 
 [[3 4]]
y_train 
 [1 2 3 4 5]
y_test 
 [6]
*********************


In [12]:
import numpy as np
from sklearn.model_selection import ShuffleSplit
X = np.arange(10)

n=0.1
#n=0.3
#n=0.5
#n=0.7
#n=0.9

ss = ShuffleSplit(n_splits=5, test_size=n,random_state=0)
for train_index, test_index in ss.split(X):
    print("%s %s" % (train_index, test_index))


[8 4 9 1 6 7 3 0 5] [2]
[5 1 2 9 8 0 6 7 4] [3]
[3 8 4 5 1 0 6 9 7] [2]
[1 9 2 7 5 8 0 3 4] [6]
[2 7 4 1 0 6 8 9 3] [5]


### 1.6.9_Stratified_Shuffle_Split

In [13]:
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 0, 1, 1, 1])
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss.get_n_splits(X, y)
print(sss)
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)
TRAIN: [2 5 1 3] TEST: [0 4]
X_train 
 [[1 2]
 [3 4]
 [3 4]
 [3 4]]
X_test 
 [[1 2]
 [1 2]]
y_train 
 [0 1 0 1]
y_test 
 [0 1]
*********************
TRAIN: [0 4 3 1] TEST: [2 5]
X_train 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1 1 0]
y_test 
 [0 1]
*********************
TRAIN: [0 4 3 1] TEST: [2 5]
X_train 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1 1 0]
y_test 
 [0 1]
*********************
TRAIN: [5 4 1 2] TEST: [0 3]
X_train 
 [[3 4]
 [1 2]
 [3 4]
 [1 2]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [1 1 0 0]
y_test 
 [0 1]
*********************
TRAIN: [1 5 2 4] TEST: [0 3]
X_train 
 [[3 4]
 [3 4]
 [1 2]
 [1 2]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1 0 1]
y_test 
 [0 1]
*********************


### 1.6.10_Time_Series_Split

In [14]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])
tscv = TimeSeriesSplit(n_splits=5)
print(tscv)
for train_index, test_index in tscv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')


TimeSeriesSplit(max_train_size=None, n_splits=5)
TRAIN: [0] TEST: [1]
X_train 
 [[1 2]]
X_test 
 [[3 4]]
y_train 
 [1]
y_test 
 [2]
*********************
TRAIN: [0 1] TEST: [2]
X_train 
 [[1 2]
 [3 4]]
X_test 
 [[1 2]]
y_train 
 [1 2]
y_test 
 [3]
*********************
TRAIN: [0 1 2] TEST: [3]
X_train 
 [[1 2]
 [3 4]
 [1 2]]
X_test 
 [[3 4]]
y_train 
 [1 2 3]
y_test 
 [4]
*********************
TRAIN: [0 1 2 3] TEST: [4]
X_train 
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]
X_test 
 [[1 2]]
y_train 
 [1 2 3 4]
y_test 
 [5]
*********************
TRAIN: [0 1 2 3 4] TEST: [5]
X_train 
 [[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]]
X_test 
 [[3 4]]
y_train 
 [1 2 3 4 5]
y_test 
 [6]
*********************
