### 1.5.1_Standard_Scaler (Standardization)

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

BreastData=load_breast_cancer()

X=BreastData.data
y=BreastData.target

scaler = StandardScaler(copy=True, with_mean=True, with_std=True)
X = scaler.fit_transform(X)

#showing data
print('X \n' , X[:10])
print('y \n' , y[:10])


X 
 [[ 1.09706398e+00 -2.07333501e+00  1.26993369e+00  9.84374905e-01
   1.56846633e+00  3.28351467e+00  2.65287398e+00  2.53247522e+00
   2.21751501e+00  2.25574689e+00  2.48973393e+00 -5.65265059e-01
   2.83303087e+00  2.48757756e+00 -2.14001647e-01  1.31686157e+00
   7.24026158e-01  6.60819941e-01  1.14875667e+00  9.07083081e-01
   1.88668963e+00 -1.35929347e+00  2.30360062e+00  2.00123749e+00
   1.30768627e+00  2.61666502e+00  2.10952635e+00  2.29607613e+00
   2.75062224e+00  1.93701461e+00]
 [ 1.82982061e+00 -3.53632408e-01  1.68595471e+00  1.90870825e+00
  -8.26962447e-01 -4.87071673e-01 -2.38458552e-02  5.48144156e-01
   1.39236330e-03 -8.68652457e-01  4.99254601e-01 -8.76243603e-01
   2.63326966e-01  7.42401948e-01 -6.05350847e-01 -6.92926270e-01
  -4.40780058e-01  2.60162067e-01 -8.05450380e-01 -9.94437403e-02
   1.80592744e+00 -3.69203222e-01  1.53512599e+00  1.89048899e+00
  -3.75611957e-01 -4.30444219e-01 -1.46748968e-01  1.08708430e+00
  -2.43889668e-01  2.81189987e-01]
 [

In [2]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
scaler.fit(data)
print(scaler.mean_)
newdata = scaler.transform(data)
print(newdata)

newdata = scaler.fit_transform(data) 
print(newdata)


[0.5 0.5]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


### 1.5.2_MinMaxScaler (Normalization)

In [3]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
scaler.fit(data)
print(scaler.data_range_)
print(scaler.data_min_)
print(scaler.data_max_)
newdata = scaler.transform(data)
print(newdata)



newdata = scaler.fit_transform(data)
print(newdata)


scaler = MinMaxScaler(feature_range = (1,5))


[ 2. 16.]
[-1.  2.]
[ 1. 18.]
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


### 1.5.3_Normalizer

In [4]:
from sklearn.preprocessing import Normalizer
X = [[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]


#transformer = Normalizer(norm='l1' )

#transformer = Normalizer(norm='l2' )

transformer = Normalizer(norm='max' )

transformer.fit(X)
transformer.transform(X)

array([[1.        , 0.25      , 0.5       , 0.5       ],
       [0.11111111, 0.33333333, 1.        , 0.33333333],
       [0.71428571, 1.        , 0.71428571, 0.14285714]])

### 1.5.4_MaxAbsScaler

In [5]:
from sklearn.preprocessing import MaxAbsScaler
X = [[ 1., 10., 2.],
     [ 2., 0., 0.],
     [ 5., 1., -1.]]
transformer = MaxAbsScaler().fit(X)
transformer
transformer.transform(X)


array([[ 0.2,  1. ,  1. ],
       [ 0.4,  0. ,  0. ],
       [ 1. ,  0.1, -0.5]])

### 1.5.5_FunctionTransformer

In [6]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

X = [[4, 1, 2, 2], [1, 3, 9, 3], [5, 7, 5, 1]]

def function1(z):
    return np.sqrt(z)

FT = FunctionTransformer(func = function1)
FT.fit(X)
newdata = FT.transform(X)
newdata


array([[2.        , 1.        , 1.41421356, 1.41421356],
       [1.        , 1.73205081, 3.        , 1.73205081],
       [2.23606798, 2.64575131, 2.23606798, 1.        ]])

### 1.5.6_Binarizer

In [7]:
from sklearn.preprocessing import Binarizer
X = [[ 1., -1., -2.],[ 2., 0., -1.], [ 0., 1., -1.]]

transformer = Binarizer(threshold=1.5 ) 
transformer.fit(X)

transformer

transformer.transform(X)


array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.]])

### 1.5.7_PolynomialFeatures

In [9]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(6).reshape(3, 2)


poly = PolynomialFeatures(degree=2 , include_bias = True)
poly.fit_transform(X)



poly = PolynomialFeatures(interaction_only=True)
poly.fit_transform(X)


array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])